"""empty message

Revision ID: d513ceb96ef9
Revises: None
Create Date: 2019-01-27 11:02:08.223998

"""

# pylint: skip-file
# revision identifiers, used by Alembic.
revision = 'd513ceb96ef9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_type',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('schema', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_type')),
    sa.UniqueConstraint('id', name=op.f('uq_entity_type_id')),
    sa.UniqueConstraint('name', name=op.f('uq_entity_type_name'))
    )
    op.create_table('entity',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('entityTypeId', sa.String(length=60), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['entityTypeId'], ['entity_type.id'], name=op.f('fk_entity_entityTypeId_entity_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity')),
    sa.UniqueConstraint('id', name=op.f('uq_entity_id'))
    )
    op.create_table('entity_audit',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('updatedEntityId', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('originalEntityContent', sa.Text(), nullable=False),
    sa.Column('changedByEntityId', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['changedByEntityId'], ['entity.id'], name=op.f('fk_entity_audit_changedByEntityId_entity')),
    sa.ForeignKeyConstraint(['updatedEntityId'], ['entity.id'], name=op.f('fk_entity_audit_updatedEntityId_entity')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_audit')),
    sa.UniqueConstraint('id', name=op.f('uq_entity_audit_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_audit')
    op.drop_table('entity')
    op.drop_table('entity_type')
    # ### end Alembic commands ###
