# pylint: skip-file
"""empty message

Revision ID: e900e60d32c6
Revises: 584bde0c29be
Create Date: 2019-01-14 18:02:36.934778

"""

# revision identifiers, used by Alembic.
revision = 'e900e60d32c6'
down_revision = '584bde0c29be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('entityTypeId', sa.String(length=60), nullable=False))
    op.drop_constraint(None, 'entity', type_='foreignkey')
    op.create_foreign_key(op.f('fk_entity_entityTypeId_entity_type'), 'entity', 'entity_type', ['entityTypeId'], ['id'])
    op.drop_column('entity', 'entityId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity', sa.Column('entityId', sa.VARCHAR(length=60), nullable=False))
    op.drop_constraint(op.f('fk_entity_entityTypeId_entity_type'), 'entity', type_='foreignkey')
    op.create_foreign_key(None, 'entity', 'entity_type', ['entityId'], ['id'])
    op.drop_column('entity', 'entityTypeId')
    # ### end Alembic commands ###
